<?php

/**
 * @file
 * Directly included by TWFY.
 */

/**
 * @file
 * THIS FILE WAS AUTOMATICALLY GENERATED BY ./rabxtophp.pl, DO NOT EDIT DIRECTLY
 *
 * mapit.php:
 * Client interface for MaPit
 *
 * Copyright (c) 2005 UK Citizens Online Democracy. All rights reserved.
 * WWW: http://www.mysociety.org
 *
 * $Id: mapit.php,v 1.59 2007/10/06 09:26:17 matthew Exp $
 *
 */

require_once 'rabx.php';

if (defined('OPTION_MAPIT_URL')) {
    $mapit_client = new RABX_Client(OPTION_MAPIT_URL,
        defined('OPTION_MAPIT_USERPWD') ? OPTION_MAPIT_USERPWD : NULL);
}

/**
 * mapit_get_voting_areas_info ARY
 *
 * As get_voting_area_info, only takes an array of ids, and returns an array
 * of hashes.
 */
function mapit_get_voting_areas_info($ary) {
    global $mapit_client;
    $params = func_get_args();
    $result = $mapit_client->call('MaPit.get_voting_areas_info', $params);
    return $result;
}

/**
 * mapit_get_voting_areas_geometry ARY [POLYGON_TYPE]
 *
 * As get_voting_area_geometry, only takes an array of ids, and returns an
 * array of hashes.
 */
function mapit_get_voting_areas_geometry($ary, $polygon_type = NULL) {
    global $mapit_client;
    $params = func_get_args();
    $result = $mapit_client->call('MaPit.get_voting_areas_geometry', $params);
    return $result;
}

/**
 * mapit_get_areas_by_type TYPE [ALL]
 *
 * Returns an array of ids of all the voting areas of type TYPE. TYPE is the
 * three letter code such as WMC. By default only gets active areas in
 * current generation, if ALL is true then gets all areas for all
 * generations.
 */
function mapit_get_areas_by_type($type, $all = NULL) {
    global $mapit_client;
    $params = func_get_args();
    $result = $mapit_client->call('MaPit.get_areas_by_type', $params);
    return $result;
}
